### ISSUE TITLE
Could be used for a map ?

### ISSUE THREAD

**Issue by JBPressac** [Daniel-KM/OpenLayersZoom#3]
Hello,
Does this plugin could be used to create a map with OpenStreetMap as a replacement of the Geolocation plugin which works only with Google Map ? Or could be extented for this usage ?
Thanks,

**Comment by Daniel-KM** [comment]
I don't think, it's designed only to display big images, but any images. On Omeka S, there is a replacement of Geolocation that use Leaflet / OpenStreetMap (and there is a plugin Leaflet for Omeka Classic too).
